### ISSUE TITLE
Mettez en place une stratégie de tests (par le Tech Lead)

### ISSUE THREAD

**Issue by charlycha** [nicowtt/Projet10_bibliotheque#3]
Après un code review de la V1 je me suis rendu compte que des tests unitaires n’ont pas été implémentés, on est donc hors des process de qualité sur cette release....

Pour la release qui est en cours de développement, merci de mettre en place une stratégie de tests pour le code API :

- Des tests unitaires pour valider les parties métiers du code API (l’utilisation de JUnit devrait faire l’affaire, à vous de voir s’il y a besoin de faire des mocks ou non) 
- Des tests d’intégration de l’API via un outil de tests d’API (ex : Postman, Soap-UI)

Pour les tests de l’application web et du batch, on verra dans un second temps. Je vous tiendrai au courant…

**Comment by nicowtt** [comment]
Afin de clôturer cette issue, la branche feature/unitTestForApi à été crée.
Des tests unitaires ont été crée sur la partie métier du code API avec une couverture de 86%.
Des tests d'integrations de l'API via l'outil de tests d'API "Postman" ont été crée:
- Réalisation d'un scénario de 12 tests d'intégrations  et 9 sans scénario afin de valider la nouvelle feature (ajout d'une liste d'attente sur chaque livre + batch)
-> ajout d'un export des test (postman) dans l'arbre principal.

La branche feature/unitTestForApi viens d'être mergé dans la branche develop.

Nicolas

![fin de la branche de test feature](https://user-images.githubusercontent.com/44237370/66901534-294b2400-efff-11e9-8cdf-f32e94c6e6ae.jpg)
